# Generated by Django 3.1.3 on 2020-11-30 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_contact_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('datefrom', models.DateField(verbose_name='From')),
                ('dateto', models.DateField(verbose_name='To')),
                ('people', models.IntegerField(verbose_name='No of People')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.destinations')),
            ],
        ),
    ]
