# Generated by Django 2.2.15 on 2020-12-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
