# Generated by Django 2.2.15 on 2020-12-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_contact_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='arriving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='leaving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
