# Generated by Django 2.2.15 on 2020-12-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20201225_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='timenow',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='timenow',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
